apiVersion: v1
kind: Service
metadata:
  name: prometheus-scc-metrics
  namespace: scc-monitoring
  labels:
    app: prometheus-scc-metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app: prometheus-scc-metrics
